ghdl -a --std=08 hdl/decodificador_3_8.vhd &&
ghdl -a --std=08 hdl/FSM.vhd &&
ghdl -a --std=08 hdl/n_register.vhd &&
ghdl -a --std=08 hdl/mux.vhd &&
ghdl -a --std=08 hdl/addsub.vhd && 
ghdl -a --std=08 hdl/mcu.vhd && 
ghdl -a --std=08 test/pkg_testing.vhd && 
ghdl -a --std=08 test/tb_mcu.vhd && 
ghdl -e --std=08 tb_mcu &&
ghdl -r --std=08 tb_mcu --wave=wave_mcu.ghw